# Generated by Django 4.2.6 on 2023-10-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('registration', models.IntegerField(verbose_name='Registration')),
            ],
        ),
    ]
